$envContent = @"
# ECONEURA ENTERPRISE CONFIGURATION
# Generated by Antigravity at initial setup

# --- GENERAL ---
NODE_ENV=development
PORT=3000

# --- FIREBASE / GOOGLE CLOUD ---
# Client configuration
VITE_FIREBASE_API_KEY=AIzaSyBI7FDSrYmGp0DSZUcf8qVw6CRwidEVvy4
VITE_FIREBASE_AUTH_DOMAIN=econeura-109cc.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=econeura-109cc
VITE_FIREBASE_STORAGE_BUCKET=econeura-109cc.firebasestorage.app

# --- SECURITY ---
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:4173,https://econeura-109cc.web.app
"@

$envContent | Out-File -Encoding UTF8 .env
Write-Host "✅ .env file created successfully with valid API Key."
